### ISSUE TITLE
HTML5 App is not visible in SaaS consumer subaccount

### ISSUE THREAD

**Issue by miyasuta** [SAP-samples/btp-developer-guide-cap#116]
## Background
I am following the tutorial : [Implement Multitenancy in a Full-Stack CAP Application Following SAP BTP Developer’s Guide](https://github.com/SAP-samples/btp-developer-guide-cap/tree/main/documentation/saas), and I am now at the last step: [Subscribe to the Application](https://github.com/SAP-samples/btp-developer-guide-cap/blob/main/documentation/saas/5-subscribe.md).
I have created a new consumer subaccount in the same region as the provider subaccount. 

## Issue
Although the subscription was successful, the HTML5 application is not visible from the consumer subaccount.
![image](https://github.com/user-attachments/assets/99e5b4d8-5051-44f8-bb70-8ea2f1ac374b)

![image](https://github.com/user-attachments/assets/f5ccc69e-c60b-48ac-bc5e-51af2cb2e035)

I have configured destinations, and the tile is visible in the consumer's Work Zone site.
![image](https://github.com/user-attachments/assets/5db5669c-b4b1-490b-81f2-23aeb3f13fbe)

However, when I press the tile, the app keeps loading, and I see that fetching ui5AppInfo.json is failing with a 404 error.
![image](https://github.com/user-attachments/assets/9505f022-1694-4774-97a3-825c0a004123)

The dependency viewer shows the following status.
![image](https://github.com/user-attachments/assets/a80cb205-6bbf-4dd4-86be-32a292457696)

Any suggestions on what might be missing?

The source code is uploaded to the following repository in the "multitenancy" branch.
https://github.com/miyasuta/incident-management-2410/tree/multitenancy

**Comment by gopalanand333** [comment]
@miyasuta 
Can you check if your application is visible in the provider account's html5 apps section? Also steps can be validated using this tutorial : https://developers.sap.com/tutorials/integrate-with-work-zone.html

**Comment by miyasuta** [comment]
@gopalanand333 
Thank you for your reply. The application is visible in the provider subaccount. Also, when I subscribed to the SaaS app in the provider subaccount, the app could be launched in SAP Build Work Zone without any issues.
![image](https://github.com/user-attachments/assets/9ab59554-ee05-45ef-b610-29f20cd90594)

**Comment by gopalanand333** [comment]
@miyasuta 
I see that your tenant mode is set to dedicated
```
  - name: incident-management-2410-auth
    type: org.cloudfoundry.managed-service
    parameters:
      config:
        tenant-mode: **dedicated**
        xsappname: incident-management-2410-${org}-${space}
      path: ./xs-security.json
      service: xsuaa
      service-plan: application
```
For multitenancy we would need **shared** mode
