### ISSUE TITLE
cds watch fails after integration with Authorization Management Service

### ISSUE THREAD

**Issue by miyasuta** [SAP-samples/btp-developer-guide-cap#119]
## Description
I am following the tutorial  [**Configure Authorization and Authentication Using the Authorization Management Service and the Identity Authentication Service**](https://github.com/SAP-samples/btp-developer-guide-cap/tree/main/documentation/xsuaa-to-ams) and am currently on the step [Integrate with Authorization Management Service](https://github.com/SAP-samples/btp-developer-guide-cap/blob/main/documentation/xsuaa-to-ams/2-integrate-with-ams.md). After completing the configurations as instructed, I encountered the following error when running `cds watch`:

## Error Output
```
[cds] - ❗️Uncaught Error [ERR_IPC_CHANNEL_CLOSED]: Channel closed
    at target.send (node:internal/child_process:754:16)
    at cds.<anonymous> (/managed-content/globals/pnpm/5/.pnpm/@sap+cds-dk@8.3.0/node_modules/@sap/cds-dk/lib/watch/watched.js:14:13)
    at Object.onceWrapper (node:events:633:26)
    at cds.emit (node:events:530:35)
    at cds.emit (/home/user/projects/incident-management-2410/node_modules/@sap/cds/lib/index.js:13:23)
    at _started (/home/user/projects/incident-management-2410/node_modules/@sap/cds/bin/serve.js:212:11)
    at /home/user/projects/incident-management-2410/node_modules/@sap/cds/bin/serve.js:205:24
    at new Promise (<anonymous>)
    at Object.serve (/home/user/projects/incident-management-2410/node_modules/@sap/cds/bin/serve.js:203:33)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 'ERR_IPC_CHANNEL_CLOSED'
}
```
Note:  `cds service` did not produce this error

## Environment
- Development Environment: SAP Business Application Studio
- Java Version Output:
```
openjdk 21.0.2 2024-01-16 LTS
OpenJDK Runtime Environment SapMachine (build 21.0.2+13-LTS)
OpenJDK 64-Bit Server VM SapMachine (build 21.0.2+13-LTS, mixed mode, sharing)
```
- `cds --version` Output:
```
@cap-js/asyncapi: 1.0.2
@cap-js/cds-types: 0.6.5
@cap-js/db-service: 1.14.0
@cap-js/hana: 1.3.2
@cap-js/openapi: 1.0.6
@cap-js/sqlite: 1.7.4
@sap/cds: 8.3.1
@sap/cds-compiler: 5.3.2
@sap/cds-dk: 8.3.0
@sap/cds-dk (global): 8.3.0
@sap/cds-fiori: 1.2.7
@sap/cds-foss: 5.0.1
@sap/cds-mtxs: 2.2.0
@sap/eslint-plugin-cds: 3.1.0
Node.js: v20.12.0
home: /home/user/projects/incident-management-2410/node_modules/@sap/cds
incident-management-2410: 1.0.0
```

- Repository: https://github.com/miyasuta/incident-management-2410/tree/ams (branch: ams)

The issue may be related to configuration or compatibility with the Authorization Management Service integration step. Any guidance or insights would be greatly appreciated.

**Comment by singhabhi1999** [comment]
Hi @miyasuta ,

Sure, will try to reproduce the issue in my environment and get back to you.

Regards,
Abhinav

**Comment by singhabhi1999** [comment]
Hi @miyasuta ,

I just cloned your app, built it, did `cds w` and its working fine for me.
<img width="1370" alt="image" src="https://github.com/user-attachments/assets/91b84146-043a-447b-af5a-8d16acfacca4">


 Please try deleting the node_modules folder, building the application again and then ty doing cds w.

Regards,
Abhinav

**Comment by miyasuta** [comment]
@singhabhi1999 
Thank you for your quick response. The issue can be reproduced with the following steps:
1. `git clone https://github.com/miyasuta/incident-management-2410.git`
2. `git fetch`
3. `git checkout ams` --> checkout ams branch
4. `npm install`
5. `cds watch` --> this is successful
6. `DEBUG=ams,ams-dev cds` --> this will generate gen/srv/ams folder
7. `cds watch` --> error

**Comment by singhabhi1999** [comment]
Hi @miyasuta ,

I have followed your steps and its working fine for me.
Since `cds watch` is working for you. There is no need to run `DEBUG=ams,ams-dev cds w` since it enables the logs from @sap/ams and @sap/ams-dev libs. So `cds w` will do the work for you.

Regards,
Abhinav

**Comment by miyasuta** [comment]
@singhabhi1999 
Thank you for your response!
I skipped `DEBUG=ams,ams-dev cds` as per your suggestion, and local authentication is working fine.

Now I have proceeded with the [Deploy and Run the Application on Cloud Foundry](https://github.com/SAP-samples/btp-developer-guide-cap/blob/main/documentation/xsuaa-to-ams/3-deploy-to-cf.md) step. However, the build failed with the following error:

```
TypeError [ERR_INVALID_ARG_TYPE]: The "paths[0]" argument must be of type string. Received undefined
    at Object.resolve (node:path:1101:7)
    at Object.to (/home/user/projects/incident-management-2410/node_modules/@sap/cds-dk/lib/build/plugin.js:136:37)
    at Object.compileCds (/home/user/projects/incident-management-2410/node_modules/@sap/ams-dev/src/cap/capAmsFlow.js:27:30)
    at async AmsBuildPlugin.build (/home/user/projects/incident-management-2410/node_modules/@sap/ams-dev/src/cap/AmsBuildPlugin.js:39:3)
    at async Promise.allSettled (index 0)
    at async BuildTaskEngine._executePipeline (/home/user/projects/incident-management-2410/node_modules/@sap/cds-dk/lib/build/buildTaskEngine.js:159:29)
    at async BuildTaskEngine._executeBuildTasks (/home/user/projects/incident-management-2410/node_modules/@sap/cds-dk/lib/build/buildTaskEngine.js:150:25)
    at async BuildTaskEngine.processTasks (/home/user/projects/incident-management-2410/node_modules/@sap/cds-dk/lib/build/buildTaskEngine.js:59:33)
    at async build (/home/user/projects/incident-management-2410/node_modules/@sap/cds-dk/lib/build/index.js:19:16)
    at async Object.build (/home/user/projects/incident-management-2410/node_modules/@sap/cds-dk/bin/build.js:171:5) {
  code: 'ERR_INVALID_ARG_TYPE'
}
```
mta.yaml is as below, and the complete code is uploaded to https://github.com/miyasuta/incident-management-2410/tree/ams (branch: ams) as before.
I would appreciate it if you could verify my settings below or provide me with a sample project with IAS settings.

```
_schema-version: 3.3.0
ID: incident-management-2410
description: A simple CAP project.
version: 1.0.0
modules:
  - name: incident-management-2410-srv
    type: nodejs
    path: gen/srv
    requires:
      - name: incident-management-2410-db
      - name: incident-management-2410-auth
        parameters:
          config:
            credential-type: "X509_GENERATED"
    provides:
      - name: srv-api
        properties:
          srv-url: ${default-url}
    parameters:
      buildpacks:
        - https://github.com/SAP/cloud-authorization-buildpack/releases/latest/download/opa_buildpack.zip 
        - nodejs_buildpack
      readiness-health-check-http-endpoint: /health
      readiness-health-check-type: http
    build-parameters:
      builder: npm
    properties:
      AMS_DCL_ROOT: "ams/dcl"
  - name: incident-management-2410-db-deployer
    type: hdb
    path: gen/db
    requires:
      - name: incident-management-2410-db
    parameters:
      buildpack: nodejs_buildpack
  - name: incident-management-2410-app-deployer
    type: com.sap.application.content
    path: .
    parameters:
      config:
        destinations:
          - forwardAuthToken: true
            HTML5.IASDependencyName: incidents-api
            name: incident-management-2410-srv-api
            url: ~{srv-api/srv-url}
          - name: ui5
            url: https://ui5.sap.com
    requires:
      - name: srv-api
      - name: incident-management-2410-auth
      - name: incident-management-2410-html5-repo-host
        parameters:
          content-target: true
    build-parameters:
      build-result: resources/
      requires:
        - artifacts:
            - nsincidents.zip
          name: nsincidents
          target-path: resources/
  - name: incident-management-2410-destination-content
    type: com.sap.application.content
    requires:
      - name: incident-management-2410-destination-service
        parameters:
          content-target: true
      - name: incident-management-2410-html5-repo-host
        parameters:
          service-key:
            name: incident-management-2410-html5-repo-host-key
      # - name: incident-management-2410-auth
      #   parameters:
      #     service-key:
      #       name: incident-management-2410-auth-key
      - name: incident-management-2410-html5-repo-runtime
        parameters:
          service-key:
            name: incident-management-2410-html5-repo-runtime-key
    parameters:
      content:
        subaccount:
          destinations:
            - Name: incident-management_cdm
              ServiceInstanceName: incident-management-2410-html5-repo-runtime
              ServiceKeyName: incident-management-2410-html5-repo-runtime-key
              URL: https://html5-apps-repo-rt.cfapps.us10.hana.ondemand.com/applications/cdm/incidents
          existing_destinations_policy: ignore
    build-parameters:
      no-source: true
  - name: nsincidents
    type: html5
    path: app/incidents
    build-parameters:
      build-result: dist
      builder: custom
      commands:
        - npm install
        - npm run build:cf
        - npm ci
        - npm run build
      supported-platforms:
        []

resources:
  - name: incident-management-2410-db
    type: com.sap.xs.hdi-container
    parameters:
      service: hana
      service-plan: hdi-shared
  - name: incident-management-2410-html5-repo-host
    type: org.cloudfoundry.managed-service
    parameters:
      service: html5-apps-repo
      service-plan: app-host
  - name: incident-management-2410-html5-repo-runtime
    type: org.cloudfoundry.managed-service
    parameters:
      service: html5-apps-repo
      service-plan: app-runtime
  # - name: incident-management-2410-auth
  #   type: org.cloudfoundry.managed-service
  #   parameters:
  #     config:
  #       tenant-mode: dedicated
  #       xsappname: incident-management-2410-${org}-${space}
  #     path: ./xs-security.json
  #     service: xsuaa
  #     service-plan: application
  - name: incident-management-2410-auth
    parameters:
      path: ./ias-config.json
      service-plan: application
      service: identity
    type: org.cloudfoundry.managed-service  
  - name: incident-management-2410-destination-service
    type: org.cloudfoundry.managed-service
    parameters:
      config:
        init_data:
          subaccount:
            destinations:
              - Authentication: NoAuthentication
                Name: incident-management-2410-rt
                ProxyType: Internet
                Type: HTTP
                URL: https://91fec855trial.launchpad.cfapps.us10.hana.ondemand.com
                CEP.HTML5contentprovider: true
            existing_destinations_policy: update
        version: 1.0.0
      service: destination
      service-name: incident-management-2410-destination-service
      service-plan: lite
parameters:
  deploy_mode: html5-repo
  enable-parallel-deployments: true
build-parameters:
  before-all:
    - builder: custom
      commands:
        - npm ci
        - npx cds build --production
        - mkdir -p resources
        - cp workzone/cdm.json resources/cdm.json
```
